name: Project build

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install latest rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true
          components: rustfmt, clippy
    - name: setup rust cache
      uses: Swatinem/rust-cache@v2
    - name: download ffmpeg
      run: |
        sudo apt install -y libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev
    - name: install java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: run cargo fmt
      working-directory: ./ayaya_native
      run: |
        cargo fmt --all -- --check
    - name: compile application
      run: make linux_jar
    - name: push release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Latest Development Build"
        files: |
          minecraft/build/libs/minecraft-1.0-SNAPSHOT-dev-all.jar
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: AyayaNativeSpigotPlugin.jar
        path: minecraft/build/libs/minecraft-1.0-SNAPSHOT-dev-all.jar
